openapi: 3.0.0
info:
  title: Wyrd Internal API
  version: 0.0.0
tags: []
paths:
  /account/auth/login/phone:
    post:
      operationId: AccountAuthAPI_login
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                  refresh:
                    type: string
                required:
                  - access
                  - refresh
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    enum:
                      - verifyIdToken is invalid.
                required:
                  - detail
        '404':
          description: The server cannot find the requested resource.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountAuthAPI.PhoneLoginBody'
  /account/auth/logout:
    delete:
      operationId: AccountAuthAPI_logout
      description: logout user in backend and remove device token
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
        '400':
          description: The server could not understand the request due to invalid syntax.
      security:
        - BearerAuth: []
  /account/auth/token/refresh:
    post:
      operationId: AccountAuthAPI_refresh
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: The server could not understand the request due to invalid syntax.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
              required:
                - refresh
      security:
        - BearerAuth: []
components:
  schemas:
    AccountAuthAPI.PhoneLoginBody:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: verifyIdToken provided by Firebase Phone Authentication. This token is used to retrieve the user's phone number.
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
